config/routes.rb
Bancos::Application.routes.draw do
  match 'bancos/eliminar_plazo' => 'bancos#eliminar_plazo'
  match 'bancos/defino_plazo' => 'bancos#defino_plazo'
  resources :bancos
  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      match 'bancos/bancos_completo' => 'bancos#bancos_completo'
      match 'bancos/:plazo_id/tasas' => 'bancos#tasas'
      match 'bancos/:id/plazos_y_tasas' => 'bancos#plazos_y_tasas'
      resources :bancos
    end
  end

   root :to => 'bancos#index'

end

app/models/banco.rb
class Banco < ActiveRecord::Base
  has_many :tasas

  attr_accessible :nombre, :tasa

  validates_presence_of :nombre, :message => 'Es requerido.'
  validates_uniqueness_of :nombre, :message => "Repetido "


  def self.banco_completo
    #regresa el listado de bancos y las tasas
    Banco.includes(:tasas).order('bancos.nombre, tasas.plazo').all

  end
end

app/models/tasa.rb
class Tasa < ActiveRecord::Base
  belongs_to :banco
  attr_accessible :plazo, :tasa, :banco_id
  validates_presence_of :plazo, :banco_id, :tasa, :message => 'Es requerido.'
  validates_uniqueness_of :plazo, :scope => [:banco_id], :message => "Repetido "

  def self.meses_a_dias(meses = 0)
    #convierte la cantidad de meses en días
    #tomando como base que las tasa se definen
    #mayormente cada 30 días (30, 60, 90...)
    meses.to_i * 30
  end

end

app/controllers/api/v1/bancos_controller.rb
class Api::V1::BancosController < ApplicationController
  # GET /bancos
  # GET /bancos.json
  def index
    @bancos = Banco.all

    respond_to do |format|
      format.json { render json: @bancos }
      format.xml { render xml: @bancos }
    end
  end

  # GET /bancos/1
  # GET /bancos/1.json
  def show
    @banco = Banco.find(params[:id])

    respond_to do |format|
      format.json { render json: @banco }
      format.xml { render xml: @banco }
    end
  end

  def plazos_y_tasas
    @banco = Banco.find(params[:id])
    @plazos = @banco.tasas.order('plazo')
    respond_to do |format|
      format.json { render json: @plazos }
      format.xml { render xml: @plazos }
    end
  end

  def tasas
    @tasa = Tasa.find(params[:plazo_id])
    respond_to do |format|
      format.json { render json: @tasa }
      format.xml { render xml: @tasa }
    end
  end

  def bancos_completo
    #regresa el listado de bancos y las tasas
    @bancos = Banco.banco_completo
    respond_to do |format|
      format.json { render json: @bancos.to_json(include: :tasas), status: :ok }
      format.xml { render xml: @bancos.to_xml(include: :tasas), status: :ok }
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bancos_controller.rb
class BancosController < ApplicationController
  # GET /bancos
  # GET /bancos.json
  def index
    @bancos = Banco.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bancos }
    end
  end

  # GET /bancos/1
  # GET /bancos/1.json
  def show
    @banco = Banco.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @banco }
    end
  end

  # GET /bancos/new
  # GET /bancos/new.json
  def new
    @banco = Banco.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @banco }
    end
  end

  # GET /bancos/1/edit
  def edit
    @banco = Banco.find(params[:id])
  end

  # POST /bancos
  # POST /bancos.json
  def create
    @banco = Banco.new(params[:banco])

    respond_to do |format|
      if @banco.save
        format.html { redirect_to @banco, notice: 'Banco was successfully created.' }
        format.json { render json: @banco, status: :created, location: @banco }
      else
        format.html { render action: "new" }
        format.json { render json: @banco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bancos/1
  # PUT /bancos/1.json
  def update
    @banco = Banco.find(params[:id])

    respond_to do |format|
      if @banco.update_attributes(params[:banco])
        format.html { redirect_to @banco, notice: 'Banco was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @banco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bancos/1
  # DELETE /bancos/1.json
  def destroy
    @banco = Banco.find(params[:id])
    @banco.destroy

    respond_to do |format|
      format.html { redirect_to bancos_url }
      format.json { head :no_content }
    end
  end

  def defino_plazo
     dias = Tasa.meses_a_dias params[:meses]
    @tasa = Tasa.new(params[:tasa])
    @tasa.plazo = dias
    @tasa.save
    @banco =  @tasa.banco
    respond_to do |format|
         format.js
     end
  end
  def eliminar_plazo
    @tasa = Tasa.find(params[:tasa_id])
    @banco= @tasa.banco
    @tasa.destroy
    respond_to do |format|
         format.js
     end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/views/bancos/_error_tasa.html.erb
<% if @tasa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tasa.errors.count, "error") %> No permite/n registrar la tasa y el plazo:</h2>

      <ul>
        <% @tasa.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/bancos/_form.html.erb
<%= form_for(@banco) do |f| %>
  <% if @banco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banco.errors.count, "error") %> prohibited this banco from being saved:</h2>

      <ul>
      <% @banco.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <div class="field">
        <%= f.label :nombre %><br />
        <%= f.text_field :nombre, :class=>"mt-1"%>
      </div>
  </div>
  <div class="form-group">
      <div class="actions">
        <%= f.submit 'Guardar', :class=>'button success' %>
      </div>
  </div>
<% end %>

app/views/bancos/_tabla_tasas.html.erb
  <legend>Listado de Plazos y Tasas</legend>
  <table id="tabla_plazos">
    <thead>
    <tr>
      <th>Plazo (Dias)</th>
      <th>Tasa</th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @banco.tasas.each do |tasa| %>
        <tr>
          <td><%= tasa.plazo %></td>
          <td><%= tasa.tasa %></td>
          <td><%= link_to 'Eliminar', {:controller=>'bancos', :action=>'eliminar_plazo', :tasa_id=>tasa.id},:remote=>true, confirm: 'Seguro elimina este registro?' %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

<script>
    $j(document).ready(function() {
        $j('#tabla_plazos').DataTable({
            responsive: true,
            colReorder: true,
            dom: 'Bfrt<"bottom"ilp<"clear">>',
            buttons: [
                {
                    extend: 'collection',
                    text: 'Exportar',
                    buttons: ['csv',
                        {
                            extend: 'excelHtml5',
                            title: 'Listado de Plazos y Tasas <%=@banco.nombre %>',
                            exportOptions: {
                                columns: ':visible'
                            }
                        },
                        {
                            extend: 'print',
                            text: 'Imprimir',
                            title: 'Listado de Plazos y Tasas <%=@banco.nombre %>',
                            exportOptions: {
                                columns: ':visible'
                            }
                        },
                        {
                            extend: 'copy',
                            text: 'Copiar',
                            exportOptions: {
                                columns: ':visible'
                            }
                        },
                        {
                            extend: 'pdfHtml5',
                            title: 'Listado de Plazos y Tasas <%=@banco.nombre %>',
                            exportOptions: {
                                columns: ':visible'
                            }


                        }


                    ]
                }
            ],
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json",
                buttons: {
                    copyTitle: 'Copiado al Portapales',
                    copySuccess: {
                        _: '%d Lineas copiadas',
                        1: '1 linea copiada'
                    }
                }
            },
            stateSave: true
        });
    } );

</script>

app/views/bancos/defino_plazo.js.erb
jQuery("#msg_error_tasa").html("<%= escape_javascript(render(:partial => 'bancos/error_tasa')) %>");
<%if @tasa.errors.blank? %>
jQuery("#tasas").html("<%= escape_javascript(render(:partial => 'tabla_tasas')) %>");
jQuery('#tasa_tasa').val('');
jQuery('#meses').val('');
<% end %>

app/views/bancos/edit.html.erb
<h1 class="text-center">Editar Banco</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @banco %> |
<%= link_to 'Regresar', bancos_path %>

app/views/bancos/eliminar_plazo.js.erb
jQuery("#tasas").html("<%= escape_javascript(render(:partial => 'tabla_tasas')) %>");

app/views/bancos/index.html.erb
<h1 class="text-center">Listado de Bancos</h1>

<table id="tabla_banco">
<thead>
  <tr>
    <th>Nombre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @bancos.each do |banco| %>
  <tr>
    <td><%= banco.nombre %></td>
    <td><%= link_to 'Mostrar', banco %></td>
    <td><%= link_to 'Editar', edit_banco_path(banco) %></td>
    <td><%= link_to 'Eliminar', banco, method: :delete, data: { confirm: 'Seguro elimina este banco?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />
<%= link_to 'Nuevo Banco', new_banco_path, :class=>'button info' %>

<script>
    $j(document).ready(function() {
        $j('#tabla_banco').DataTable({
            responsive: true,
            colReorder: true,
            dom: 'Bfrt<"bottom"ilp<"clear">>',
            buttons: [
                {
                    extend: 'colvis',
                    text: 'Columnas Visibles'
                },
                {
                    extend: 'collection',
                    text: 'Exportar',
                    buttons: ['csv',
                        {
                            extend: 'excelHtml5',
                            title: 'Listado de bancos',
                            exportOptions: {
                                columns: ':visible'
                            }
                        },
                        {
                            extend: 'print',
                            text: 'Imprimir',
                            title: 'Listado de bancos',
                            exportOptions: {
                                columns: ':visible'
                            }
                        },
                        {
                            extend: 'copy',
                            text: 'Copiar',
                            exportOptions: {
                                columns: ':visible'
                            }
                        },
                        {
                            extend: 'pdfHtml5',
                            title: 'Listado de bancos',
                            exportOptions: {
                                columns: ':visible'
                            }


                        }


                    ]
                }
            ],
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json",
                buttons: {
                    copyTitle: 'Copiado al Portapales',
                    copySuccess: {
                        _: '%d Lineas copiadas',
                        1: '1 linea copiada'
                    }
                }
            },
            stateSave: true
        });
    } );

</script>

app/views/bancos/new.html.erb
<h1 class="text-center">Nuevo Banco</h1>

<%= render 'form' %>

<%= link_to 'Regresar', bancos_path %>

app/views/bancos/show.html.erb
<p id="notice"><%= notice %></p>
<h1 class="text-center">Datos del Banco</h1>

<fieldset class="fieldset_border">
<p>
  <b class="display2">Nombre:</b>
  <b class="display1"><%= @banco.nombre %></b>
</p>

</fieldset>

<%= link_to 'Editar', edit_banco_path(@banco) %> |
<%= link_to 'Regresar', bancos_path %>
<br/>
<br/>
<input id="mostrar_form_tasa" type="button" value="Definir Plazo y Tasa" class="button info">

<fieldset style="display:none" id="form_tasa" class="fieldset_border">
  <div id="msg_error_tasa"></div>
  <%= form_tag({:controller=>'bancos', :action=>'defino_plazo'}, :id => "form_imputacion", :remote=> true) %>
  <div class="row">
      <input name="tasa[banco_id]" type="hidden" id="tasa_banco_id" value="<%= @banco.id%>">
    <div class="cell-md-6">
        <label>Plazo (Meses):</label>
        <input name="meses" type="number" id="meses" class="mt-1">
      </div>
    <div class="cell-md-6">
        <label>Tasa:</label>
        <input name="tasa[tasa]" type="text" id="tasa_tasa" class="mt-1">
      </div>
  </div>
  <br/>
  <div class="form-group">
    <%= submit_tag 'Agregar',  :class=>'button success'  %>
    <input id="cancelar_form_tasa" type="button" value="Cancelar" class="button alert">
  </div>
</fieldset>
<fieldset id="tasas" class="fieldset_border">
  <%= render :partial=>'tabla_tasas'%>
</fieldset>


<script type="text/javascript">
    $j(document).ready(function()
    {
        $j("#mostrar_form_tasa").on( "click", function() {
            $j('#form_tasa').toggle();
        });
        $j("#cancelar_form_tasa").on( "click", function() {
            $j('#form_tasa').toggle();
        });
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bancos</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-all.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.18/css/jquery.dataTables.min.css"/>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css"/>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/colreorder/1.5.0/css/colReorder.dataTables.min.css"/>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedheader/3.1.4/css/fixedHeader.dataTables.min.css"/>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/keytable/2.4.0/css/keyTable.dataTables.min.css"/>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.2/css/responsive.dataTables.min.css"/>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.2.6/css/select.dataTables.min.css"/>




  <%= javascript_include_tag "application" %>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdn.metroui.org.ua/v4/js/metro.min.js"></script>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/b-1.5.2/b-flash-1.5.2/b-html5-1.5.2/datatables.min.css"/>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>


  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/colreorder/1.5.0/js/dataTables.colReorder.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/fixedheader/3.1.4/js/dataTables.fixedHeader.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/keytable/2.4.0/js/dataTables.keyTable.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.2/js/dataTables.responsive.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/select/1.2.6/js/dataTables.select.min.js"></script>


  <script>
      var $j = jQuery.noConflict();
  </script>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>